### ISSUE TITLE
[BUG] unescape() is deprecated

### ISSUE THREAD

**Issue by Wintus** [dreamos82/chrome_parameters#121]
# bug

Unicode-encoded strings in params get mojibake.

# code

https://github.com/dreamos82/chrome_parameters/blob/73ea3cf308e0883bd177edecf6ab511931cf500f/src/popup.js#L270

## fix

It would be a solution to fix this by using `decodeURIComponent` like this:

```js
function decodeQueryParam(p) {
  return decodeURIComponent(p.replace(/\+/g, ' '));
}

decodeQueryParam('search+query');
```

# ref

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/unescape

> Usually, `decodeURI` or `decodeURIComponent` are preferred over `unescape`.

> Note: Do not use `unescape` to decode URIs, use `decodeURI` instead.

**Comment by dreamos82** [comment]
Hi wintus, 

thanks you for your bug and your suggestion, since you proposed already a solution, i htink it would be fair to you to open a PR and i will review and merge it in the coming days. But if you don't have time or don't want i'll test you suggested code and fix it in coupole of days. 

Thanks again!

**Comment by Wintus** [comment]
Sure, I'm gonna try to submit a PR on it in a upcoming week!

**Comment by dreamos82** [comment]
Thank you @Wintus
