### ISSUE TITLE
Replace string buttons with icons and update main icon

### ISSUE THREAD

**Issue by inuyasha82** [dreamos82/chrome_parameters#35]
Replace string buttons with icons.

**Comment by dreamos82** [comment]
There is no real need to replace the text with icons, could be nice just to improve the buttons look and feel, especially since the dark mode is being implemented the buttons will lose quality (since i lost the original uncompressed files). 

The extension main icon now doesn't look very well in dark mode (black on black) is barely visible, and after many tries to have an icon that depends on the theme (refer to the discussion in #94 ) i found t hat is much easier to create a new icon that looks well on both themes,  saving lot of hassle.

**Comment by dreamos82** [comment]
Done in #104 thanks to @3rdvision
