### ISSUE TITLE
Add dark mode icon option to settings

### ISSUE THREAD

**Issue by 3rdvision** [dreamos82/chrome_parameters#94]
Add extra option to use a gray or white icon instead of the default.
This is useful for people using dark mode themes in which the icon is not really visible. See picture below
![image](https://user-images.githubusercontent.com/24736423/98394938-655e8600-2053-11eb-80cd-bc2db1f7bd3d.png)

**Comment by dreamos82** [comment]
Yeah it looks like a good idea. 

I'll see if it is possible to do it (because that is the extension icon declared in the manifest, so i need to see if is possible to change it runtime, after having iidentified if i'm on dark/light mode. 

I'll put it in the next milestone!

**Comment by dreamos82** [comment]
Hi @3rdvision, i'm not sure if you are still following this issuer, or you are interested in it. 

I finally had time to start to draft a dark mode option for the extension.  

Here a the screenshots for firefox and chrome:

* Firefox 
![screenshotfirefox](https://user-images.githubusercontent.com/59960116/108006957-a8d27400-6ff4-11eb-8228-adfe6ccd9099.png)

* Chrome
![Screenshot at 2021-02-16 01-02-30](https://user-images.githubusercontent.com/59960116/108006977-bbe54400-6ff4-11eb-84c7-6cec0df37f7d.png)


What do you think? Do you have any suggestion? 

If you want to play with it i pushed the changed on the branch: https://github.com/dreamos82/chrome_parameters/tree/94_add_dark_mode 

one problem i have to solve is that when i remove the background color, from the buttons images (yes they are images) the shadow effect disappear, and they look little bit more flatter (even in light mode), so i need probably to find a way to preserve the same look and feel, or maybe get rid of the images and use just text.

**Comment by 3rdvision** [comment]
Yes I am @dreamos82 and I like your extension better than any other in this market of url parameters.

Looks pretty cool!

I like the button images even without the shadow effect. Loses that special touch but gains a minimalistic look.

I would just also change the main image logo button to be brither in case you have a different theme but I don't know if that is possible.


Either way I think this is a plus.
I will try this tomorrow if I have some time left and give more feedback.

Thank you! 🙏

**Comment by dreamos82** [comment]
I @3rdvision thanks for your feedback, i have to ask you a favor if you can, i mostly implemented the dark mode on the extension with the following features: 

1. By default the selected theme reflect the system theme. So if u are using a system in dark mode, then the extensioin will be in dark mode.
2. Otherwise i added an options section (open the extension look at the bottom right corner, just below "Create a bug/suggestion" where the user can switch between light and dark theme or use the system theme. This option override the default behaviour, and will be used everytime the extension starts. 

Now on my system for some reason firefox correctly detect the system theme setting the relevant media variable, but chrome not (my idea is that probably is because i'm using XFCE as window manager, and for some reason probably the dark mode of XFCE is not read correctly by chrome). 

So if you have time i would appreciate if you can download this version of the extension and test it, to see if it works using the system values, and also customizing them, plus any feedback on the UI will be appreciated. 

If you need help on loading an external extension just ask me i will provide you the information you will need. 
It's pretty straightforward by the way, you can start from here: 
* Chrome: chrome://extensions
* Firefox: about:debugging then select addons

And of course if you find any problem please report them.

**Comment by 3rdvision** [comment]
> Now on my system for some reason firefox correctly detect the system theme setting the relevant media variable, but chrome not (my idea is that probably is because i'm using XFCE as window manager, and for some reason probably the dark mode of XFCE is not read correctly by chrome).

I tested on Firefox 83.0 and it's working but not in Chromium 87.0. I'm using Plasma 5.20.3.
Not sure what's causing it but I can reproduce what you said.

Also, changing theme in settings doesn't seem to be having the desired effect:
![image](https://user-images.githubusercontent.com/24736423/108344316-e5f55c80-71d4-11eb-870c-8e2be917280d.png)

**Comment by dreamos82** [comment]
ahah @3rdvision Thanks! My fault, i finished it yesterday night, and forgot to mention the custom setting is not active yet on the popup, but only on the options page, and appartently it is working there. 

Ok i'll fix it later   and will ask you again some feedback (and looks like i need to fix also the colors for chromium on the options page!!!)

**Comment by dreamos82** [comment]
@3rdvision juist committed more changes, now it should work, and also the popup will should correctly load the theme. 

By the way i did some research and looks like that the problem of prefers-color-scheme not correctly update for chrome on linux, is quite common (i googled it and many people are reporting this behaviour). 

Btw so far i think that the workaround will be selectr manually the theme to be used. 

I tried the extension on a mac on chrome and it is working as expected (The laptop theme is dark and the extension is loaded with dark theme). 

I need to still do some minor improvements, but i think that most of the code now is done for the dark/light theme.l (wow didn't expected this change to be pretty big, to have an idea of the changes done so far you can have a look at the PR #101).

Let me know what do you think, or if you still encounter problems.

**Comment by dreamos82** [comment]
So @3rdvision i spent some time in trying to understand how to change the icon depending on the style selected by the user (dark/light), that was also the main request of this issue.

Actually the only solution that i found is to to use the browser.pageAction.setIcon function, that needs as a parameter the tabId, and getting it is an asyncronous query, and it also means that i need to update the icon on every single tab. So basically everytime u switch the tab there will be something like: 

```
chrome.tabs.query({
    active: true,
    lastFocusedWindow: true
}, function(tabs) {
   //Code to update the icon
    var tab = tabs[0];
    console.log(tab.url);
    alert(tab.url);
});
```

And i'm not even sure that it is going to update the icon until the popup isn't open. Btw i prefer to avoid to have to call the code to change icon on every single tabswitch/popup open, so i'm trying to figure out an alternative, method if possible, otherwise i'm not sure i want to implement that kind of change, even the extension is small, i'm trying to avoid to add that kind of code when possible. 

I posted a question on stackoverflow to see if there is a better solution: https://stackoverflow.com/questions/66294732/chrome-firefox-extension-write-on-internal-extension-filesystem 

Probably another compromise solutioon is to create an icon that looks nice on both dark and light mode. (but i'm not good with graphic, so i should need help from someone that has nice ideas :D )

**Comment by 3rdvision** [comment]
> Probably another compromise solutioon is to create an icon that looks nice on both dark and light mode.

I might help with that when I have some free time. Do you remember what font you uses for the icon's text labels?
Could be the most effective solution to this, just by changing the icon's color to something gray or anything that can be visible in different themes.
Also, do you know if it's possible to use a vector of SVG format as an icon image instead of using png?

**Comment by dreamos82** [comment]
Hi @3rdvision, 


i really would appreciate if you can help me on improviing the icons! And yeah probably doing an icon that looks nice on both is the best idea (i tried to make one but was very ugly XD) 
You can refer to the issue #35 (but even if it mentions using icons, strings are still ok, you can do whataever you think is better and easier for you) 

Unfortunately i don't remember what was the font used, the icons were created by a friend of mine, and i don't even have the original psd files (there is a branch called artworks where you can find all the actual icons used in png format). Maybe it looks similar to Comic Sans? (but maybe i can be wrong :) ) 

For the svg vector i did some experiments and in theory yes is supported at least in firefox, but in chrome there is a long time issue open since 2009, requesting svg icons to be supported (and from what i understood they should be supported since they are supported by webkit) but in 2021 still not solved yed, https://bugs.chromium.org/p/chromium/issues/detail?id=29683

I was thinking to the svg icon because with it you can use css style, and was hoping that then i can use the 

```
@media( prefers-color-scheme: dark|light) 
```

directive, but i did some experiments in firefox, and apparently it is not working, in chrome the icon doesn't even shows up! :) 

So let me know if you can do the icon and/or the buttons! :) 

And thanks for the interest!

**Comment by 3rdvision** [comment]
Sorry about the delay.
I'd like to present this alternative using 50% gray color no shadow.

![icon](https://user-images.githubusercontent.com/24736423/111153558-03c2a100-858a-11eb-8df9-6d88c3d988f9.png)

This is a transparent PNG 80x80 image with ~3kb, like to the original.

The font I being used is Smiling Cat.

I have the SVG files and can replicate to the other icons and labels.

**Comment by dreamos82** [comment]
Hey @3rdvision huge thanks for the icon, tested on chrome and firefox and looks pretty cool. 

Yeah if you want and have time you can update also the other labels,

The extension also need another icon of the size 128x128, can you do it? 

Once done if you want you can create a PR with the new icons against master to update them, 
 and another one against artworks only with the images updated. I'll be more than happy to merge them! 

And thanks again!!!

**Comment by dreamos82** [comment]
I think all the work is done here, we can close it! :) 
Thanks for your help and contributions @3rdvision
